feature: improve os detection for inventory page
voxpupuli/puppetboard pull request #712
Opened 2022-09-12 07:08 UTC by melck

Hello,

I wanted to use inventory page but it only works with few linux OS. Here is my proposal to support many OS. I have introduced a new parameter named `INVENTORY_FACT_TEMPLATES` to keep customization. This parameter is used to customize cell display using jinja. Default INVENTORY_FACTS has been changed to use trusted and os facts.

 It has been tested with Puppet agent >= 5 to 7:
- Windows (Pro, Server 2012/2016/2019)
- MacOS
- Debian Family (Debian, Ubunut, Linux Mint, etc.)
- Redhat Family (RedHat Enterprise, Oracle Linux, CentOS)
- Suze Family (SUZE Enterprise)

With puppet agent 4, windows os will display nothing.

It should fix #485. 

What do you think about this changes ?

2022-09-16 10:56 UTC, bastelfreak reviewed
to me the change looks fine, but someone with more Python knowledge should take a look as well. @sebastianrakel could you take a look?

2022-09-24 10:21 UTC, gdubicki requested changes
I found some time. :) The MR looks good to me except one minor comment about the docs.

2022-09-24 10:21 UTC, gdubicki commented on README.md
> +- `INVENTORY_FACT_TEMPLATES`: A mapping between fact name and jinja template to customize display
This line should probably be added one line lower.

2022-09-24 10:23 UTC, merged

2022-09-27 12:38 UTC, gdubicki commented
I have pre-released this in [v4.1.0rc3](https://github.com/voxpupuli/puppetboard/releases/tag/v4.1.0rc3). It would be great if we could add a screenshot of the Inventory view showing nodes with various OSes for the final v4.1.0 release that I would like to do in a few days. Can you provide such screenshot, @melck? I don't have nodes with other OS than Linux in my infrastructure...