Restore and refactor facts filtering
voxpupuli/puppetboard pull request #716
Opened 2022-09-26 10:34 UTC by melck

that has been removed in #708

Fixes #714

2022-09-26 15:23 UTC, gdubicki commented
Cool, it’s good to get rid of a technology if it’s used for one thing only. :) 

So it will be functionally the same as before?

2022-09-26 15:25 UTC, gdubicki requested changes
Can you please also remove coffeescript from dev.py and possibly other references?

2022-09-27 07:35 UTC, melck commented
Hello @gdubicki ,

I got rid of all related coffeescript things. Since the file `dev.py` was only useful to handle coffeescript compilation, i removed it to use default flask command. I updated dev docs in consequences.

Regarding functionnality, it will be the same but i have added a sightly delay (250ms) for filtering to avoid weird freeze of browsers when typing to fast.

2022-09-27 10:21 UTC, gdubicki approved these changes

2022-09-27 10:23 UTC, merged